In [24]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [25]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [26]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [27]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [28]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [29]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [30]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

dep=dataset['classification_yes']

In [31]:
dataset["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [32]:
indep.shape

(399, 27)

In [33]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [34]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [38]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_)    

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [39]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}

In [40]:
table=pd.DataFrame.from_dict(re)

In [41]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024994,1.249726e-02,0.006249,0.007653,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.953846,0.971429,0.984615,0.969697,1.000000,0.975917,0.015502,7
1,0.193705,1.593050e-02,0.028118,0.006248,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.969697,0.957746,0.968750,0.985075,0.985075,0.973269,0.010515,9
2,0.021870,7.653137e-03,0.006249,0.007653,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.970588,1.000000,0.952381,0.969697,0.969697,0.972473,0.015365,11
3,0.190580,1.530489e-02,0.018746,0.006249,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.969697,0.985507,0.952381,0.985075,1.000000,0.978532,0.016213,5
4,0.021870,7.651736e-03,0.003124,0.006249,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.969697,0.985507,0.952381,0.985075,1.000000,0.978532,0.016213,5
5,0.193704,7.653449e-03,0.018745,0.006249,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.985507,0.968750,0.985075,0.985075,0.984881,0.009892,1
6,0.021870,7.652942e-03,0.009373,0.007653,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.985075,0.971429,0.952381,0.985075,0.984615,0.975715,0.012785,8
7,0.209326,2.538108e-02,0.018744,0.006249,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",1.000000,0.957746,0.952381,0.985075,1.000000,0.979040,0.020392,4
8,0.015621,9.464947e-07,0.006248,0.007653,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.953846,0.957746,0.918033,0.985075,1.000000,0.962940,0.028248,12
9,0.202342,1.484416e-02,0.021872,0.007655,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.957746,0.968750,0.985075,1.000000,0.982314,0.016857,2
10,0.018746,6.247735e-03,0.003124,0.006248,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.955224,0.985075,0.952381,0.985075,0.985075,0.972566,0.015347,10
11,0.194178,6.409715e-03,0.018745,0.006249,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.957746,0.984615,0.969697,0.985075,0.979427,0.014469,3

In [42]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}: 0.9924946382275899

In [43]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [44]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [46]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC Normal 0 or 1:"))
pc_normal_input=float(input("PC Normal 0 or 1:"))
pcc_present_input=float(input("PC Present 0 or 1:"))
ba_present_input=float(input("BA_Present 0 or 1:"))
htn_yes_input=float(input("HTN 0 or 1:"))
dm_yes_input=float(input("DM 0 or 1:"))
cad_yes_input=float(input("CAD 0 or 1:"))
appet_yes_input=float(input("Appet 0 or 1:"))
pe_yes_input=float(input("PE 0 or 1:"))
ane_yes_input=float(input("ANE 0 or 1:"))

Age:25
BP:90
AL:1
SU:3
BGR:45
BU:344
SC:565
SOD:345
POT:564
HRMO:232
PCV:75
WC:232
RC:5675
SG_B:232
SG_C:232
SG_D:45
SG_E:5456
RBC Normal 0 or 1:0
PC Normal 0 or 1:1
PC Present 0 or 1:1
BA_Present 0 or 1:0
HTN 0 or 1:0
DM 0 or 1:1
CAD 0 or 1:0
Appet 0 or 1:1
PE 0 or 1:1
ANE 0 or 1:1

In [47]:
RF=grid.predict([[age_input,bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input,
                  hrmo_input, pcv_input, wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, 
                  rbc_normal_input, pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, 
                  cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]]) 
print("Future_Prediction={}".format(RF))

Future_Prediction=[1]

In [48]:
print("If output, Yes = Paitent has Chronic Kidney Diseases, No = Paitent doesn't has CKD")
print('')
print("Has Paitent affected by Chronic Kidney Diseases?")
print('')
if(RF==1):    
    print("Yes")
else:
    print("No")

If output, Yes = Paitent has Chronic Kidney Diseases, No = Paitent doesn't has CKD

Has Paitent affected by Chronic Kidney Diseases?

Yes